config/routes.rb
Tracksapp::Application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'
  
  match 'login' => 'login#login'
  match 'login/expire_session' => 'login#expire_session'
  match 'login/check_expiry' => 'login#check_expiry'
  match 'logout' => 'login#logout'
  
  match "tickler" => "todos#list_deferred"
  match 'review' => "projects#review"
  match 'calendar' => "todos#calendar"
  match 'done' => "stats#done", :as => 'done_overview'
  
  match 'search' => 'search#index'
  match 'search/results' => 'search#results', :via => 'post'

  match 'data' => "data#index"
  match 'data/csv_notes' => 'data#csv_notes'
  match 'data/yaml_export' => 'data#yaml_export'
  match 'data/xml_export' => 'data#xml_export'
  match 'data/csv_actions' => 'data#csv_actions'
  
  match 'integrations' => "integrations#index"
  match 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  match 'integrations/cloudmailin' => 'integrations#cloudmailin'
  match 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'
  match 'integrations/google_gadget.xml' => 'integrations#google_gadget', :as => 'google_gadget'
  match 'integrations/get_applescript1.js' => 'integrations#get_applescript1'
  match 'integrations/get_applescript2.js' => 'integrations#get_applescript2'
  match 'integrations/get_quicksilver_applescript.js' => 'integrations#get_quicksilver_applescript'
  
  match 'preferences' => "preferences#index"
  match 'preferences/render_date_format' => "preferences#render_date_format"
  
  match 'feeds' => "feedlist#index", :as => 'feeds'
  match 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  match 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'
  
  match 'stats' => 'stats#index'
  match 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  match 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  match 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  match 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  match 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  match 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  match 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  match 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  match 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  match 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  match 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  match 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  match 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  match 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  match 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'
  
  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end
  
  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end
  
  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end
  match 'todos/tag/:name' => 'todos#tag', :as => :tag
  match 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'

  match 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  match 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  match 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  match 'mobile' => 'todos#index', :format => 'm'
  match 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end
  
  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  match 'signup' => "users#new"
  
  resources :notes
  resources :preferences
      
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  attr_protected :user

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_filter :set_source_view

  def index
    @all_notes = current_user.notes.all
    @count = @all_notes.size
    @page_title = "TRACKS::All notes"
    @source_view = 'note_list'
    respond_to do |format|
      format.html
      format.xml { render :xml => @all_notes.to_xml( :except => :user_id )  }
    end
  end

  def show
    @note = current_user.notes.find(params['id'])
    @page_title = "TRACKS::Note " + @note.id.to_s
    respond_to do |format|
      format.html
      format.m
    end
  end

  def create
    @note = current_user.notes.build
    @note.attributes = params["note"]

    @saved = @note.save

    respond_to do |format|
      format.js
      format.xml do
        if @saved
          head :created, :location => note_url(@note), :text => "new note with id #{@note.id}"
        else
          render_failure @note.errors.full_messages.join(', ')
        end
      end
      format.html do
        render :text => 'unexpected request for html rendering'
      end
    end
  end

  def update
    @note = current_user.notes.find(params['id'])
    @note.attributes = params["note"]
    @saved = @note.save
    respond_to do |format|
      format.html
      format.js { render }
    end
  end

  def destroy
    @note = current_user.notes.find(params['id'])
    @note.destroy
    
    respond_to do |format|
      format.html
      format.js { @down_count = current_user.notes.size }
    end
  end

  protected

  def set_source_view
    @source_view = params['_source_view'] || 'note'
  end

end

app/helpers/notes_helper.rb
module NotesHelper
  def truncated_note(note, characters = 50)
    sanitize(textilize_without_paragraph(truncate(note.body, :length => characters, :omission => "...")))
  end

  def rendered_note(note)
    sanitize(textilize_without_paragraph(note.body))
  end

  def link_to_delete_note(note, descriptor = sanitize(note.id.to_s))
    link_to(
      descriptor,
      note_path(note, :format => 'js'),
      {:id => "delete_note_#{note.id}", :class => "delete_note_button",
        :title => t('notes.delete_note_title', :id => note.id), :x_confirm_message => t('notes.delete_note_confirm', :id => note.id)}
    )
  end

end

app/views/notes/_note.html.erb
<div class="container" id="note-<%= note.id %>-wrapper">
  <div id="<%= dom_id(note, 'container') %>">

    <h2><%= link_to(t('notes.note_header', :id => note.id.to_s), note, :title => t('notes.note_link_title', :id => note.id.to_s)) %></h2>

    <div class="project_notes" id="<%= dom_id(note) %>">
      <%= render :partial => "notes/note_details", :object => note %>
    </div>

    <div id="<%= dom_id(note, 'edit') %>" class="note-edit-form" style="display:none">
      <%= render :partial => "notes/note_edit_form", :object => note %>
    </div>

  </div>
</div>

app/views/notes/_note.m.erb
<div class="mobile_note">
  <%= sanitize(textilize_without_paragraph(note.body)) %>
</div>
<div class="mobile_note_info">
  <br/>
  <%= link_to(t('notes.note_location_link') + note.project.name, project_path(note.project, :format => 'm')) %>
  <%= Note.human_attribute_name('created_at') %>: <%= format_date(note.created_at) %>
  <% if note.updated_at? -%>
  &nbsp;|&nbsp;<%= Note.human_attribute_name('updated_at') %>: <%= format_date(note.updated_at) %>
<% end -%>
</div>
<% note = nil -%>

app/views/notes/_note_details.html.erb
<% note = note_details -%>
<div class="note_boby"><%= Tracks::Utils.render_text(note.body) %></div>

<div class="note_footer">

  <%= link_to_delete_note(note, image_tag( "blank.png",:title => t('notes.delete_item_title'), :class=>"delete_item")) %> &nbsp;
  <%= link_to_edit_note(note, image_tag( "blank.png", :title => t('notes.edit_item_title'), :class=>"edit_item") ) %>

  | <%= link_to(t('notes.in_project') + note.project.name, note.project, :class=>"footer_link" ) %>&nbsp;|&nbsp;

  <%= Note.human_attribute_name('created_at') %>: <%= format_date(note.created_at) %>

  <% if note.updated_at? -%>
    &nbsp;|&nbsp;<%= Note.human_attribute_name('updated_at') %>: <%= format_date(note.updated_at) %>
  <% end -%>
</div>

app/views/notes/_note_edit_form.html.erb
<%
submit_text ||= t('common.update')
note = note_edit_form
-%><%=
form_for(note, :html => {
    :id => dom_id(note, 'edit_form'),
    :class => "inline-form edit-note-form"}) do |f|
-%>

  <div id="error_status"><%= get_list_of_error_messages_for(note) %></div>

  <%= f.hidden_field( "project_id" ) %>
  <%= f.text_area( "body", "cols" => 70, "rows" => 15, "tabindex" => 1 ) %>

  <div class="submit_box">
    <div class="widgets">
      <button type="submit" class="positive" id="<%= dom_id(note, 'submit') %>" tabindex="15">
        <%=image_tag("accept.png", :alt => "") %>
        <%= submit_text %>
      </button>
      <a href="" class="negative" id="neg_<%=dom_id(note, 'edit_form')%>">
        <%=image_tag("cancel.png", :alt => "") %>
        <%= t 'common.cancel' %>
      </a>
    </div>
  </div>

  <br/><br/>

<% end -%>

app/views/notes/_notes_summary.html.erb
<% note = notes_summary -%>
<div class="note_wrapper" id="<%= dom_id(note) %>">
<div class="note_link">
<%= link_to( 
  image_tag("blank.png", :border => 0),
  note,
  :title => t('notes.show_note_title'),
  :class => "link_to_notes icon",
  :id => dom_id(note, "link")) %></div>
<div class="note_note"><%= rendered_note(note) %></div>
</div>
<% note = nil -%>

app/views/notes/_notes_summary.m.erb
<% note = notes_summary -%>
<div class="note"><%= link_to( truncated_note(note), note_path(note, :format => 'm')) %></div>
<% note = nil -%>

app/views/notes/create.js.erb
<% if @saved -%>
  TracksPages.hide_errors();
  add_note();
  clear_form();
<% else -%>
  TracksPages.show_errors(html_for_error_messages());
<% end -%>

function add_note() {
  $('div#notes').append(html_for_note_summary());
  $('#empty-n').hide();
}

function clear_form() {
  $('#new-note').hide();
  $('#edit-note-form').clearForm();
}

function html_for_error_messages() {
  return "<%= escape_javascript(get_list_of_error_messages_for(@note)) %>";
}

function html_for_note_summary() {
  return "<%= @saved ? escape_javascript(render(:partial => 'notes_summary', :object => @note)) : "" %>";
}

app/views/notes/destroy.js.erb
remove_deleted_note();
TracksPages.set_page_badge(<%=@down_count%>);
TracksPages.page_notify('notice', "<%=  t('notes.deleted_note', :id => @note.id)%>", 5);

function remove_deleted_note() {
  $('div#note-<%=@note.id%>-wrapper').slideUp(1000,
    function() {
      $('div#note-<%=@note.id%>-wrapper').remove();
    });
}

app/views/notes/index.html.erb
<div id="display_box_projects">
  <% if @all_notes.empty? -%>
    <div class="message"><p><%= t('notes.no_notes_available') %></p></div>
  <% else -%>
    <%= render :partial => @all_notes %>
  <% end -%>
</div>

app/views/notes/show.html.erb
<div id="display_box_projects">
  <%= render :partial => @note %>
</div>

app/views/notes/show.m.erb
<%= render :partial => @note %>

app/views/notes/update.js.erb
<% if @saved -%>

  TracksPages.hide_errors();
  TracksPages.page_notify('notice', 'Note <%=@note.id %> saved', 5);
  replace_note_form_with_updated_note();

<% else -%>
  TracksPages.show_errors(html_for_error_messages());
<% end %>

function replace_note_form_with_updated_note() {
  $('#<%= dom_id(@note, 'edit')%>').fadeOut(250, function() {
    $('#<%= dom_id(@note, 'edit')%>').html(html_for_updated_note_form());
    $('div.project_notes#<%= dom_id(@note)%>').html(html_for_updated_note_details());
    $('#<%= dom_id(@note)%>').fadeIn(500);
  });
}

function html_for_error_messages() {
  return "<%= escape_javascript(get_list_of_error_messages_for(@note)) %>";
}

function html_for_updated_note_form(){
  return "<%= escape_javascript(render(:partial => 'note_edit_form', :object => @note)) %>";
}

function html_for_updated_note_details(){
  return "<%= escape_javascript(render(:partial => 'note_details', :object => @note)) %>";
}