config/routes.rb
Tracksapp::Application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'
  
  match 'login' => 'login#login'
  match 'login/expire_session' => 'login#expire_session'
  match 'login/check_expiry' => 'login#check_expiry'
  match 'logout' => 'login#logout'
  
  match "tickler" => "todos#list_deferred"
  match 'review' => "projects#review"
  match 'calendar' => "todos#calendar"
  match 'done' => "stats#done", :as => 'done_overview'
  
  match 'search' => 'search#index'
  match 'search/results' => 'search#results', :via => 'post'

  match 'data' => "data#index"
  match 'data/csv_notes' => 'data#csv_notes'
  match 'data/yaml_export' => 'data#yaml_export'
  match 'data/xml_export' => 'data#xml_export'
  match 'data/csv_actions' => 'data#csv_actions'
  
  match 'integrations' => "integrations#index"
  match 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  match 'integrations/cloudmailin' => 'integrations#cloudmailin'
  match 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'
  match 'integrations/google_gadget.xml' => 'integrations#google_gadget', :as => 'google_gadget'
  match 'integrations/get_applescript1.js' => 'integrations#get_applescript1'
  match 'integrations/get_applescript2.js' => 'integrations#get_applescript2'
  match 'integrations/get_quicksilver_applescript.js' => 'integrations#get_quicksilver_applescript'
  
  match 'preferences' => "preferences#index"
  match 'preferences/render_date_format' => "preferences#render_date_format"
  
  match 'feeds' => "feedlist#index", :as => 'feeds'
  match 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  match 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'
  
  match 'stats' => 'stats#index'
  match 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  match 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  match 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  match 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  match 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  match 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  match 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  match 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  match 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  match 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  match 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  match 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  match 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  match 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  match 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'
  
  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end
  
  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end
  
  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end
  match 'todos/tag/:name' => 'todos#tag', :as => :tag
  match 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'

  match 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  match 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  match 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  match 'mobile' => 'todos#index', :format => 'm'
  match 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end
  
  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  match 'signup' => "users#new"
  
  resources :notes
  resources :preferences
      
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  helper :todos, :application, :notes, :projects, :contexts
  
  def results
    @source_view = params['_source_view'] || 'search'
    @page_title = "TRACKS::Search Results for #{params[:search]}"
    terms = "%#{params[:search]}%"

    @found_not_complete_todos = current_user.todos.
      where("(todos.description LIKE ? OR todos.notes LIKE ?) AND todos.completed_at IS NULL", terms, terms).
      includes(Todo::DEFAULT_INCLUDES).
      reorder("todos.due IS NULL, todos.due ASC, todos.created_at ASC").
      all
    
    @found_complete_todos = current_user.todos.
      where("(todos.description LIKE ? OR todos.notes LIKE ?) AND NOT (todos.completed_at IS NULL)", terms, terms).
      includes(Todo::DEFAULT_INCLUDES).
      reorder("todos.completed_at DESC").
      all
      
    @found_todos = @found_not_complete_todos + @found_complete_todos

    @found_projects = current_user.projects.where("name LIKE ? OR description LIKE ?", terms, terms).all
    @found_notes = current_user.notes.where("body LIKE ?", terms).all
    @found_contexts = current_user.contexts.where("name LIKE ?", terms).all
    
    # TODO: limit search to tags on todos
    @found_tags = Tagging.find_by_sql([
        "SELECT DISTINCT tags.name as name "+
          "FROM tags "+
          "LEFT JOIN taggings ON tags.id = taggings.tag_id "+
          "LEFT JOIN todos ON taggings.taggable_id = todos.id "+
          "WHERE todos.user_id=? "+
          "AND tags.name LIKE ? ", current_user.id, terms])

    @count = @found_todos.size  + @found_projects.size + @found_notes.size + @found_contexts.size + @found_tags.size

    init_not_done_counts
    init_project_hidden_todo_counts
  end

  def index
    @page_title = "TRACKS::Search"
  end

  def init
    @source_view = params['_source_view'] || 'search'
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_show_results_collection.html.erb
<%
collection = show_results_collection
collection_name ||= 'unknown'
collection_title ||= 'unknown object'
unless collection.empty?
-%>
  <div id="<%=collection_name%>-container" class="container">
    <h2><span id="<%=collection_name%>" class="badge"><%= collection.size %></span><%= collection_title %></h2>
    <%= yield %>
  </div>
<% end -%>

app/views/search/index.html.erb
<div id="display_box_search">
  <%= form_tag(search_results_path, :id => 'search-form') do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag t('common.search') %>
  <% end %>
</div>

app/views/search/results.html.erb
<% if @count == 0 -%>
  <div class="message"><p><%= t('search.no_results') %></p></div>
<% else -%>

  <%= render :layout => 'show_results_collection', :object => @found_todos, :locals => { :collection_name => "found-todos", :collection_title => t('search.todos_matching_query')} do %>
    <%= render :partial => "todos/todo", :collection => @found_todos, :locals => { :parent_container_type => 'search', :suppress_context => false, :suppress_project => false, :suppress_edit_button => false } %>
  <% end -%>

  <%= render :layout => 'show_results_collection', :object => @found_projects, :locals => { :collection_name => "found-project", :collection_title => t('search.projects_matching_query')} do %>
    <%= render :partial => "projects/project_listing", :collection => @found_projects, :locals => { :suppress_drag_handle => true, :suppress_edit_button => true, :suppress_delete_button => true } %>
  <% end -%>

  <%= render :layout => 'show_results_collection', :object => @found_notes, :locals => { :collection_name => "found-notes", :collection_title => t('search.notes_matching_query')} do %>
    <%= render :partial => "notes/notes_summary", :collection=> @found_notes %>
  <% end -%>

  <%= render :layout => 'show_results_collection', :object => @found_contexts, :locals => { :collection_name => "found-contexts", :collection_title => t('search.contexts_matching_query')} do %>
    <%= render :partial => "contexts/context_listing", :collection => @found_contexts, :locals => { :suppress_drag_handle => true, :suppress_edit_button => true } %>
  <% end -%>

  <%= render :layout => 'show_results_collection', :object => @found_tags, :locals => { :collection_name => "found-tags", :collection_title => t('search.tags_matching_query')} do %>
    <span class="tags"><%  @found_tags.each do |tag| -%>
        <span class="tag"><%= link_to tag.name, tag_path(tag.name) -%></span>
      <% end %>
    </span><br/><br/>
  <% end -%>

<% end -%>